### ISSUE TITLE
fsType should be 0

### ISSUE THREAD

**Issue by davelab6** [jasperdewaard/Proza-Libre#30]
fsType should be 0

**Comment by jasperdewaard** [comment]
Was fixed by Dave :)

**Comment by davelab6** [comment]
Sorry, you still need to fix it upstream, otherwise I get a regression when I pull your update :) ExtraBold is not 0

**Comment by jasperdewaard** [comment]
Ahh, I see. Should be fixed now.

Cheers,

Jasper de Waard
——————
Bureau Roffa
