### ISSUE TITLE
Tag + Versioning

### ISSUE THREAD

**Issue by davelab6** [jasperdewaard/Proza-Libre#35]
You might like to tag a commit (and perhaps make a release using the Github release feature) at this point, as the TTF fonts as they are now will go into Google Fonts :) 

Please also increment the version number's minor number in the files as part of the next update :)

**Comment by jasperdewaard** [comment]
I don’t know how to tag a commit but I just made a release. When can I expect to see them on Google Fonts?

Cheers,

Jasper de Waard
——————
Bureau Roffa

**Comment by davelab6** [comment]
Github has tagged it for you :) 

<img width="670" alt="screen shot 2016-05-25 at 09 13 21" src="https://cloud.githubusercontent.com/assets/261579/15541129/f22cf6d2-2258-11e6-8772-42caa74409ba.png">

I can't give a specific release date, but soon :)

**Comment by davelab6** [comment]
ah! So, the way this works, when you make a release github provides a link with text "source code" to a ZIP with the complete state of the repo at that point in time. 

You can OPTIONALLY add files to the release, such that if your repo contained only source files you could attach a binary compiled version to go along with the sources zip and be downloaded individually. However since you have the binary fonts in `/fonts` this is not needed. 

Please visit https://github.com/jasperdewaard/Proza-Libre/releases again and remove all the files you attached.

**Comment by davelab6** [comment]
> Please visit jasperdewaard/Proza-Libre/releases again and remove all the files you attached.

This hasn't happened but that's OK, I'll close this out now :)
